#!/usr/bin/env bash
#
# setup-sudo.sh — install a scoped NOPASSWD sudo rule so opencode-anycli
# sessions can run package-manager commands without an interactive
# password prompt.
#
# Why this exists:
#   The cline subprocess (and opencode's bash tool inside it) does not
#   reliably forward a TTY to the commands it spawns. So sudo prompts
#   typed inside an opencode-anycli session usually never reach the
#   user's terminal — sudo errors out with "no tty" or hangs.
#
#   The standard, secure workaround is a /etc/sudoers.d entry that
#   whitelists ONLY the specific commands the agent needs (NOT
#   `NOPASSWD: ALL`). This script auto-detects the user's package
#   manager and installs that whitelist.
#
# Usage:
#   bash scripts/setup-sudo.sh         # interactive: detect + confirm + apply
#   bash scripts/setup-sudo.sh --yes   # non-interactive: apply without prompt
#   bash scripts/setup-sudo.sh --remove   # remove the rule
#   bash scripts/setup-sudo.sh --print     # print what would be applied, do not write
#
set -euo pipefail

ASSUME_YES=0
REMOVE=0
PRINT_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --yes|-y) ASSUME_YES=1 ;;
    --remove) REMOVE=1 ;;
    --print)  PRINT_ONLY=1 ;;
    -h|--help)
      sed -n '3,28p' "$0"
      exit 0 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

if [ -t 1 ] && [ "${NO_COLOR:-0}" != "1" ]; then
  G=$'\033[1;32m'; Y=$'\033[1;33m'; R=$'\033[1;31m'; B=$'\033[1;34m'; D=$'\033[2m'; N=$'\033[0m'
else
  G=""; Y=""; R=""; B=""; D=""; N=""
fi

SUDOERS_FILE="/etc/sudoers.d/opencode-anycli"

# ─── Remove path ──────────────────────────────────────────────────────────────
if [ "$REMOVE" -eq 1 ]; then
  if [ ! -f "$SUDOERS_FILE" ]; then
    printf "%bℹ%b %s does not exist; nothing to remove.\n" "$B" "$N" "$SUDOERS_FILE"
    exit 0
  fi
  printf "%b▶%b Removing %s (requires sudo)...\n" "$B" "$N" "$SUDOERS_FILE"
  sudo rm -f "$SUDOERS_FILE"
  printf "%b✓%b Removed.\n" "$G" "$N"
  exit 0
fi

# ─── Detect platform ──────────────────────────────────────────────────────────
OS_NAME="$(uname -s)"
case "$OS_NAME" in
  Darwin)
    printf "%bℹ%b macOS detected. Homebrew typically does not require sudo;\n" "$B" "$N"
    printf "  no sudoers rule is needed for normal package installs.\n"
    printf "  If you specifically need sudo for system commands, edit\n"
    printf "  %s manually with the commands you trust.\n" "$SUDOERS_FILE"
    exit 0
    ;;
  Linux) ;;
  *) printf "%b✗%b Unsupported OS: %s\n" "$R" "$N" "$OS_NAME"; exit 1 ;;
esac

# ─── Detect package manager ───────────────────────────────────────────────────
PMS=""
DISTRO=""
if command -v apt-get >/dev/null 2>&1; then
  DISTRO="Debian/Ubuntu"
  for c in apt-get apt dpkg add-apt-repository; do
    p="$(command -v "$c" 2>/dev/null || true)"
    [ -n "$p" ] && PMS="${PMS:+$PMS, }$p"
  done
elif command -v dnf >/dev/null 2>&1; then
  DISTRO="Fedora/RHEL (dnf)"
  for c in dnf rpm yum; do
    p="$(command -v "$c" 2>/dev/null || true)"
    [ -n "$p" ] && PMS="${PMS:+$PMS, }$p"
  done
elif command -v yum >/dev/null 2>&1; then
  DISTRO="RHEL/CentOS (yum)"
  for c in yum rpm; do
    p="$(command -v "$c" 2>/dev/null || true)"
    [ -n "$p" ] && PMS="${PMS:+$PMS, }$p"
  done
elif command -v pacman >/dev/null 2>&1; then
  DISTRO="Arch"
  for c in pacman; do
    p="$(command -v "$c" 2>/dev/null || true)"
    [ -n "$p" ] && PMS="${PMS:+$PMS, }$p"
  done
elif command -v zypper >/dev/null 2>&1; then
  DISTRO="openSUSE"
  for c in zypper rpm; do
    p="$(command -v "$c" 2>/dev/null || true)"
    [ -n "$p" ] && PMS="${PMS:+$PMS, }$p"
  done
elif command -v apk >/dev/null 2>&1; then
  DISTRO="Alpine"
  PMS="$(command -v apk)"
else
  printf "%b✗%b Could not detect a known package manager.\n" "$R" "$N"
  printf "  Edit %s manually with the specific commands you need.\n" "$SUDOERS_FILE"
  exit 1
fi

if [ -z "$PMS" ]; then
  printf "%b✗%b Detected %s but found no package-manager binaries on PATH.\n" "$R" "$N" "$DISTRO"
  exit 1
fi

# Build the sudoers content.
RULE_CONTENT="$(cat <<EOF
# Generated by opencode-anycli setup-sudo on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Allows ${USER} to run the following commands without a password from
# inside an opencode-anycli session. The cline subprocess does not
# forward a TTY to its bash subprocesses, so interactive sudo prompts
# fail; this rule is the standard, scoped workaround.
#
# Detected distro: ${DISTRO}
#
# To remove: sudo rm ${SUDOERS_FILE}
#         or: bash ${0} --remove
${USER} ALL=(ALL) NOPASSWD: ${PMS}
EOF
)"

# ─── Print-only path ──────────────────────────────────────────────────────────
if [ "$PRINT_ONLY" -eq 1 ]; then
  printf "%b▶%b Would write to %s%b%s%b:\n\n" "$B" "$N" "$D" "$SUDOERS_FILE" "$N" ""
  printf "%s\n\n" "$RULE_CONTENT"
  printf "%bRun without --print to apply.%b\n" "$D" "$N"
  exit 0
fi

# ─── Show + confirm + apply ───────────────────────────────────────────────────
printf "%b▶%b Detected: %s\n" "$B" "$N" "$DISTRO"
printf "%b▶%b Will write %b%s%b allowing user %b%s%b to run:\n" \
  "$B" "$N" "$D" "$SUDOERS_FILE" "$N" "$D" "$USER" "$N"
printf "    %s\n" "$PMS"
printf "  (without password, only for these specific commands.)\n\n"

if [ "$ASSUME_YES" -ne 1 ]; then
  if [ ! -t 0 ]; then
    printf "%b✗%b Non-interactive shell. Re-run with --yes to apply.\n" "$R" "$N"
    exit 1
  fi
  printf "%b?%b Apply this rule? [y/N] " "$Y" "$N"
  read -r reply
  case "$reply" in y|Y|yes|YES) ;; *) printf "Aborted.\n"; exit 0 ;; esac
fi

TMPF="$(mktemp)"
trap 'rm -f "$TMPF"' EXIT
printf "%s\n" "$RULE_CONTENT" > "$TMPF"

# Validate with visudo BEFORE installing.
if ! sudo visudo -c -f "$TMPF" >/dev/null 2>&1; then
  printf "%b✗%b Generated sudoers file failed visudo syntax check.\n" "$R" "$N"
  printf "  This is a bug — please report. The bad file is at: %s\n" "$TMPF"
  trap - EXIT
  exit 1
fi

sudo install -m 0440 "$TMPF" "$SUDOERS_FILE"
printf "%b✓%b Installed %s\n" "$G" "$N" "$SUDOERS_FILE"

# Verify the rule is now active.
if sudo -n -l 2>&1 | grep -q "NOPASSWD"; then
  printf "%b✓%b sudo -l confirms NOPASSWD entry is active.\n" "$G" "$N"
else
  printf "%b⚠%b sudo -l did not show the entry. You may need to log out and back in.\n" "$Y" "$N"
fi

cat <<EOF

${G}Done.${N} opencode-anycli sessions can now run these commands without
a password prompt:

    ${PMS}

To remove the rule later:
    sudo rm ${SUDOERS_FILE}
    # or:
    bash $0 --remove

If you need additional commands whitelisted, add them to the same file
manually with sudo visudo (do NOT use NOPASSWD: ALL — keep the list scoped).
EOF
